#!/usr/bin/env python3
"""Build a workflow.scripps.edu-importable workflow zip from a Python recipe.

A workflow zip looks like::

    <workflow-name>.zip
    +-- <workflow-name>.json          # graph: connections + content + metadata
    +-- NODE_<process>_<hex>.zip      # one bundle per Process node referenced
    +-- NODE_<widget>_<hex>.zip       # one bundle per Input widget
    +-- NODE_tag_<key>_<hex>.zip      # one bundle per inserted tag node

This module exposes the :class:`Workflow` DSL plus :func:`Workflow.export`
which materializes the whole tree on disk + zips it. Recipes live under
``workflows/`` (see ``workflows/nmr_predictor.py`` for a worked example).

Design notes / conventions
==========================

* **Process nodes** come from :data:`tools.export_nodes.NODES` — they
  reference the live ``scripps_workflow.nodes.*`` implementations via
  the same shim (``script.sh`` + ``script.py``) the node exporter
  produces. To add a new process node to a workflow, register it in
  ``NODES`` first.

* **Widgets** ("Number", "Combo box", "Check box", "Text") are pure
  GUI sources — no script, just a single output socket. They are
  declared with :meth:`Workflow.widget`.

* **Tag nodes** are auto-inserted whenever a widget feeds into a Process
  node's *named* config input (i.e. anything other than the upstream
  pointer). Each tag instance bundles a tiny per-instance ``tag_input.py``
  with ``KEY = "<config_key>"`` baked in (matching the GUI's existing
  per-instance convention so the engine can run them with no extra
  install). The constant edit pattern is exactly what the imported
  example used.

* **Pointer connections** are declared with :meth:`Workflow.pointer`.
  The DSL forces the destination input to be ``"pointer JSON"``, since
  that's the canonical name we baked into ``tools/export_nodes.py``.

* **node_id** values are sha1-derived from each node's *display name*
  in the workflow (Process node names come from their ``wf-*``
  identifier; widgets and tag instances use the alias / key the recipe
  picked). This keeps IDs internally consistent across the per-node
  bundles and the workflow's content/connection records — the engine's
  importer is expected to remap on the way in, but they must resolve
  inside the bundle.

Stdlib only.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import secrets
import shutil
import sys
import tempfile
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

# Allow ``python tools/export_workflow.py`` from anywhere in the repo.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tools.export_nodes import (  # noqa: E402
    DEFAULT_ENV_PY,
    DEFAULT_HOST,
    DEFAULT_VERSION,
    NODES,
    NodeSpec,
    build_metadata,
    derive_input_id,
    derive_node_id,
    derive_output_id,
    render_script_py,
    render_script_sh,
)


# ---------------------------------------------------------------------------
# Widget kinds + tag template
# ---------------------------------------------------------------------------

def _slugify(label: str) -> str:
    """Make a label safe for use as a filename / node identifier."""
    out = []
    prev_underscore = False
    for ch in label:
        if ch.isalnum():
            out.append(ch)
            prev_underscore = False
        else:
            if not prev_underscore:
                out.append("_")
            prev_underscore = True
    return "".join(out).strip("_") or "widget"


WIDGET_CATEGORIES = {
    "text": "Text",
    "number": "Number",
    "combo": "Combo box",
    "checkbox": "Check box",
}

# Per-instance tag node script. The KEY is baked in so the engine can run
# this without any package install — same shape as the example workflow's
# tag bundles. argv[1] = the upstream value.
TAG_SCRIPT_TEMPLATE = '''\
#!/usr/bin/env python3
"""tag_input.py (per-instance) — emits ``{key}=<value>`` on stdout.

Generated by tools/export_workflow.py. The KEY constant is baked in for
this specific tag node instance; edit the recipe and re-export rather
than hand-editing this file.
"""
from __future__ import annotations

import sys


KEY = "{key}"


def main() -> int:
    value = sys.argv[1] if len(sys.argv) > 1 else ""
    sys.stdout.write(f"{{KEY}}={{value}}\\n")
    sys.stdout.flush()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


# ---------------------------------------------------------------------------
# DSL nodes
# ---------------------------------------------------------------------------

@dataclass
class _Placement:
    """One node instance in the workflow's content[] array."""

    workflow_content_id: int
    name: str               # display name in the workflow
    node_type: str          # "Process" | "Input"
    category: str           # "Script" | "Number" | "Combo box" | ...
    node_id: int
    x: int
    y: int
    alias: str | None = None
    default_value: str = ""
    help_value: str | None = None
    inputs: list[dict] = field(default_factory=list)
    outputs: list[dict] = field(default_factory=list)


@dataclass
class _Widget:
    placement: _Placement
    output_id: int
    output_name: str
    output_type: str        # "text" | "number"


@dataclass
class _Process:
    placement: _Placement
    spec: NodeSpec | None     # None = synthetic (e.g. a tag node)
    is_tag: bool = False
    tag_key: str | None = None
    # Map of input/output name -> id, copied from the placement's
    # `inputs` / `outputs` records so connection-builders can lookup
    # by string key without re-scanning lists.
    input_ids: dict[str, int] = field(default_factory=dict)
    output_ids: dict[str, int] = field(default_factory=dict)
    # Per-instance overrides for the GUI ``type`` field of named inputs.
    # Empty for stock process nodes; populated for tag instances so the
    # ``value`` socket carries the upstream widget's kind (e.g. number).
    input_types: dict[str, str] = field(default_factory=dict)


@dataclass
class _Connection:
    workflow_connection_id: int
    src: _Placement
    dst: _Placement
    from_output: int
    to_input: int
    output_name: str
    input_name: str


# ---------------------------------------------------------------------------
# Workflow DSL
# ---------------------------------------------------------------------------

class Workflow:
    """A single workflow recipe.

    Usage::

        wf = Workflow(name="NMR Predictor", description="...")
        smiles = wf.widget("text", alias="SMILES", default="", at=(-90, 225))
        embed  = wf.process("wf-embed", at=(180, 225))
        wf.pointer(smiles, embed, port="smiles")  # widget -> source process
        ...
        wf.export(Path("dist/workflows"), zip_=True)

    See ``workflows/nmr_predictor.py`` for the full pattern.
    """

    def __init__(
        self,
        *,
        name: str,
        description: str = "",
        domain: str = "private",
        revision: str = "na",
        version: str = "1.0.1",
        host: str = DEFAULT_HOST,
        node_version: str = DEFAULT_VERSION,
        env_py: str = DEFAULT_ENV_PY,
    ):
        self.name = name
        self.description = description
        self.domain = domain
        self.revision = revision
        self.version = version
        self.host = host
        self.node_version = node_version
        self.env_py = env_py

        self._widgets: list[_Widget] = []
        self._processes: list[_Process] = []
        self._connections: list[_Connection] = []
        # Auto-incrementing id pools (must be unique within one workflow).
        self._content_seq = 1_000_000
        self._connection_seq = 1_000_000
        # name -> _Widget / _Process for de-dup of identical placements.
        self._widget_index: dict[str, _Widget] = {}

    # ---- node placement -------------------------------------------------

    def widget(
        self,
        kind: str,
        *,
        alias: str,
        default: str = "",
        at: tuple[int, int] = (0, 0),
        name: str | None = None,
        output_name: str | None = None,
        help_text: str | None = None,
    ) -> _Widget:
        """Place a GUI input widget.

        :param kind: ``"text" | "number" | "combo" | "checkbox"``.
        :param alias: Label rendered in the GUI.
        :param default: Default value (string for the engine).
        :param at: ``(x, y)`` placement coordinates.
        :param name: Internal node name. Defaults to the alias.
        :param output_name: Socket label. Defaults to ``alias``.
        """
        if kind not in WIDGET_CATEGORIES:
            raise ValueError(f"Unknown widget kind: {kind!r}")
        category = WIDGET_CATEGORIES[kind]
        # Sanitize derived names for use as filenames inside the zip.
        node_name = name or _slugify(alias)
        if node_name in self._widget_index:
            return self._widget_index[node_name]

        out_name = output_name or alias
        out_type = "number" if kind == "number" else "text"

        node_id = derive_node_id(node_name)
        out_id = derive_output_id(node_name, out_name)
        x, y = at

        placement = _Placement(
            workflow_content_id=self._next_content_id(),
            name=node_name,
            node_type="Input",
            category=category,
            node_id=node_id,
            x=x,
            y=y,
            alias=alias,
            default_value=default,
            help_value=help_text,
            inputs=[],
            outputs=[{
                "node_output_id": out_id,
                "node_id": node_id,
                "name": out_name,
                "type": out_type,
                "tags": "",
            }],
        )
        widget = _Widget(placement=placement, output_id=out_id,
                         output_name=out_name, output_type=out_type)
        self._widgets.append(widget)
        self._widget_index[node_name] = widget
        return widget

    def process(
        self,
        wf_name: str,
        *,
        at: tuple[int, int] = (0, 0),
        alias: str | None = None,
    ) -> _Process:
        """Place a Process node by its ``wf-*`` registry name."""
        if wf_name not in NODES:
            raise ValueError(f"Unknown process: {wf_name!r}. "
                             f"Available: {', '.join(sorted(NODES))}")
        spec = NODES[wf_name]
        return self._add_process_from_spec(spec, at=at, alias=alias)

    def _add_process_from_spec(
        self, spec: NodeSpec, *, at: tuple[int, int],
        alias: str | None = None, is_tag: bool = False,
        tag_key: str | None = None,
        input_types: dict[str, str] | None = None,
    ) -> _Process:
        node_name = spec.name
        node_id = derive_node_id(node_name)
        x, y = at

        inputs_named = list(spec.inputs)
        if not spec.is_source:
            inputs_named = ["pointer JSON", *inputs_named]

        input_types = input_types or {}
        input_records = [
            {
                "node_input_id": derive_input_id(node_name, n),
                "node_id": node_id,
                "name": n,
                "type": input_types.get(n, "text"),
                "tags": "",
                "required": 1 if (n == "pointer JSON" and not spec.is_source) else 0,
            }
            for n in inputs_named
        ]
        output_records = [
            {
                "node_output_id": derive_output_id(node_name, n),
                "node_id": node_id,
                "name": n,
                "type": "text",
                "tags": spec.output_tags,
            }
            for n in spec.outputs
        ]

        placement = _Placement(
            workflow_content_id=self._next_content_id(),
            name=node_name,
            node_type="Process",
            category=spec.category,
            node_id=node_id,
            x=x,
            y=y,
            alias=alias,
            inputs=input_records,
            outputs=output_records,
        )

        proc = _Process(
            placement=placement,
            spec=spec,
            is_tag=is_tag,
            tag_key=tag_key,
            input_ids={r["name"]: r["node_input_id"] for r in input_records},
            output_ids={r["name"]: r["node_output_id"] for r in output_records},
            input_types=dict(input_types),
        )
        self._processes.append(proc)
        return proc

    # ---- wiring ---------------------------------------------------------

    def pointer(
        self,
        src: _Widget | _Process,
        dst: _Process,
        *,
        port: str = "pointer JSON",
    ) -> None:
        """Connect a pointer (or text source) -> a Process node's named input.

        For source-process nodes (smiles_to_3d, tag_input) you can pass a
        widget as ``src`` and override ``port`` with the actual socket
        name (e.g. ``port="smiles"``).
        """
        if isinstance(src, _Widget):
            src_placement = src.placement
            src_output_id = src.output_id
            src_output_name = src.output_name
        else:
            src_placement = src.placement
            # Process nodes have a single canonical "pointer JSON" output.
            assert src.spec is not None
            out_name = src.spec.outputs[0]
            src_output_id = src.output_ids[out_name]
            src_output_name = out_name

        if port not in dst.input_ids:
            raise KeyError(f"{dst.placement.name!r} has no input named {port!r}. "
                           f"Available: {sorted(dst.input_ids)}")

        self._connections.append(_Connection(
            workflow_connection_id=self._next_connection_id(),
            src=src_placement,
            dst=dst.placement,
            from_output=src_output_id,
            to_input=dst.input_ids[port],
            output_name=src_output_name,
            input_name=port,
        ))

    def bind(
        self,
        widget: _Widget,
        *,
        to: _Process | Iterable[_Process],
        key: str,
        tag_at: tuple[int, int] | None = None,
    ) -> _Process:
        """Wire a widget into one or more Process nodes via an auto-tag node.

        Inserts (once per widget+key) a synthetic ``tag_<key>`` node that
        emits ``"<key>=<value>"`` on stdout, then connects the widget to
        the tag node and the tag node to each ``to`` process's named
        input ``key``.

        :param widget: GUI widget supplying the value.
        :param to: One process or an iterable of processes that need
            ``<key>`` set on their argv.
        :param key: Name of the config key the consumers expect.
        :param tag_at: Optional ``(x, y)`` for the tag-node placement.
            Defaults to placing the tag a bit to the right of the widget.
        """
        targets = [to] if isinstance(to, _Process) else list(to)
        if not targets:
            raise ValueError("bind() needs at least one target process")

        tag = self._get_or_make_tag(
            key, at=tag_at, near=widget.placement,
            value_type=widget.output_type,
        )

        # Widget -> tag (one connection regardless of fan-out)
        if not any(c.src is widget.placement and c.dst is tag.placement
                   for c in self._connections):
            self._connections.append(_Connection(
                workflow_connection_id=self._next_connection_id(),
                src=widget.placement,
                dst=tag.placement,
                from_output=widget.output_id,
                to_input=tag.input_ids["value"],
                output_name=widget.output_name,
                input_name="value",
            ))

        # Tag -> each consumer. Tag nodes emit on the canonical "stdout"
        # output socket (engine convention); the *content* is a key=value
        # token, communicated downstream as the input_name on the
        # consumer side.
        tag_out_name = tag.spec.outputs[0] if tag.spec else "stdout"
        tag_out_id = tag.output_ids[tag_out_name]
        for proc in targets:
            if key not in proc.input_ids:
                raise KeyError(
                    f"{proc.placement.name!r} has no config input {key!r}. "
                    f"Available: {sorted(n for n in proc.input_ids if n != 'pointer JSON')}"
                )
            self._connections.append(_Connection(
                workflow_connection_id=self._next_connection_id(),
                src=tag.placement,
                dst=proc.placement,
                from_output=tag_out_id,
                to_input=proc.input_ids[key],
                output_name=tag_out_name,
                input_name=key,
            ))
        return tag

    def _get_or_make_tag(
        self, key: str, *, at: tuple[int, int] | None,
        near: _Placement | None,
        value_type: str = "text",
    ) -> _Process:
        tag_name = f"tag_{key}"
        for p in self._processes:
            if p.is_tag and p.tag_key == key:
                return p
        # Synthesize a NodeSpec for the tag instance. Tag nodes emit on
        # the engine's canonical "stdout" socket with empty tags — the
        # downstream consumer's input_name carries the semantic ("the
        # token I'm receiving is for config key X").
        spec = NodeSpec(
            name=tag_name,
            module="tag_input",
            description=f'Tag value with "{key}=".',
            is_source=True,           # tag nodes don't take a pointer
            inputs=["value"],
            outputs=["stdout"],
            output_tags="",
            category="Script",
        )
        if at is None:
            if near is not None:
                at = (near.x + 150, near.y)
            else:
                at = (0, 0)
        return self._add_process_from_spec(
            spec, at=at, is_tag=True, tag_key=key,
            input_types={"value": value_type},
        )

    # ---- id pools -------------------------------------------------------

    def _next_content_id(self) -> int:
        self._content_seq += 1
        return self._content_seq

    def _next_connection_id(self) -> int:
        self._connection_seq += 1
        return self._connection_seq

    # ---- export ---------------------------------------------------------

    def to_dict(self) -> dict:
        """Render the workflow to its JSON-shaped dict (without zipping)."""
        wf_id = int(hashlib.sha1(self.name.encode()).hexdigest()[:7], 16)
        # Workflow-level metadata fields the GUI auto-creates on first save
        # (Name / Debug / Number). Including them here keeps round-trip
        # imports happy: the engine appears to expect their presence and
        # surfaces them in the run-launcher panel.
        metadata = [
            {"workflow_metadata_id": 1, "workflow_id": wf_id,
             "name": "Name",   "type": "text",   "required": 0},
            {"workflow_metadata_id": 2, "workflow_id": wf_id,
             "name": "Debug",  "type": "text",   "required": 0},
            {"workflow_metadata_id": 3, "workflow_id": wf_id,
             "name": "Number", "type": "number", "required": 0},
        ]
        return {
            "workflow_id": wf_id,
            "name": self.name,
            "code": None,
            "description": self.description,
            "domain": self.domain,
            "revision": self.revision,
            "author": None,
            "workflow_favorite_status": 0,
            "connections": [self._render_connection(c, wf_id) for c in self._connections],
            "content": [self._render_placement(p, wf_id) for p in self._all_placements()],
            "metadata": metadata,
            "version": self.version,
            "host": self.host,
        }

    def _all_placements(self) -> list[_Placement]:
        return [w.placement for w in self._widgets] + [p.placement for p in self._processes]

    def _render_placement(self, p: _Placement, wf_id: int) -> dict:
        return {
            "workflow_content_id": p.workflow_content_id,
            "workflow_id": wf_id,
            "node_id": p.node_id,
            "x_axis": p.x,
            "y_axis": p.y,
            "alias": p.alias,
            "default_value": p.default_value,
            "help_value": p.help_value,
            "node_type": p.node_type,
            "category": p.category,
            "name": p.name,
            "domain": "private",
            "author": None,
            "inputs": p.inputs,
            "outputs": p.outputs,
            "node_params_data": [],
        }

    def _render_connection(self, c: _Connection, wf_id: int) -> dict:
        return {
            "workflow_connection_id": c.workflow_connection_id,
            "workflow_id": wf_id,
            "from": c.src.workflow_content_id,
            "to": c.dst.workflow_content_id,
            "from_output": c.from_output,
            "to_input": c.to_input,
            "output_name": c.output_name,
            "input_name": c.input_name,
        }

    def export(
        self,
        out_dir: Path,
        *,
        zip_: bool = True,
        keep_dir: bool = True,
    ) -> Path:
        """Materialize bundles + emit ``<workflow>.zip`` under ``out_dir``.

        :returns: Path to the workflow zip (or to the staged directory if
            ``zip_`` is False).
        """
        out_dir = Path(out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        # Stage everything in a temp dir we can zip atomically.
        stage = Path(tempfile.mkdtemp(prefix="wf_export_", dir=out_dir))
        try:
            wf_json = stage / f"{self.name}.json"
            wf_json.write_text(
                json.dumps(self.to_dict(), indent=2) + "\n",
                encoding="utf-8",
            )

            for proc in self._processes:
                self._write_process_bundle(proc, stage)
            for widget in self._widgets:
                self._write_widget_bundle(widget, stage)

            if zip_:
                zip_path = out_dir / f"{self.name}.zip"
                with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
                    for p in sorted(stage.iterdir()):
                        zf.write(p, arcname=p.name)
                if not keep_dir:
                    shutil.rmtree(stage)
                else:
                    final_dir = out_dir / self.name
                    if final_dir.exists():
                        shutil.rmtree(final_dir)
                    stage.rename(final_dir)
                return zip_path

            final_dir = out_dir / self.name
            if final_dir.exists():
                shutil.rmtree(final_dir)
            stage.rename(final_dir)
            return final_dir
        except Exception:
            shutil.rmtree(stage, ignore_errors=True)
            raise

    # ---- per-bundle writers --------------------------------------------

    def _write_process_bundle(self, proc: _Process, stage: Path) -> None:
        spec = proc.spec
        assert spec is not None
        node_id = proc.placement.node_id

        with tempfile.TemporaryDirectory(dir=stage) as tmp:
            tmp_path = Path(tmp)
            json_path = tmp_path / f"{proc.placement.name}.json"
            sub_dir = tmp_path / str(node_id)
            sub_dir.mkdir()

            metadata = build_metadata(
                spec, env_py=self.env_py, host=self.host,
                version=self.node_version, node_id=node_id,
                input_types=proc.input_types or None,
            )
            # Override name + description for tag instances so the GUI
            # shows ``tag_<key>`` instead of the bare ``tag_input`` name.
            metadata["name"] = proc.placement.name
            metadata["description"] = spec.description

            if proc.is_tag:
                # Per-instance script: tag_input.py with KEY baked in.
                script_path = sub_dir / "tag_input.py"
                script_path.write_text(
                    TAG_SCRIPT_TEMPLATE.format(key=proc.tag_key),
                    encoding="utf-8",
                )
                script_path.chmod(0o755)
                metadata["node_value"] = "tag_input.py"
                metadata["files_info"] = [{
                    "node_files_info_id": 1,
                    "node_id": node_id,
                    "file_name": "tag_input.py",
                    "file_format": "python",
                    "upload_method": "file",
                    "path": f"{node_id}/tag_input.py",
                }]
            else:
                # script.sh + script.py shim (same as tools/export_nodes.py).
                sh_path = sub_dir / "script.sh"
                sh_path.write_text(render_script_sh(self.env_py), encoding="utf-8")
                sh_path.chmod(0o755)
                py_path = sub_dir / "script.py"
                py_path.write_text(render_script_py(spec, self.env_py), encoding="utf-8")
                py_path.chmod(0o755)
                # files_info already correct for script.sh / script.py.

            json_path.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")

            zip_name = f"NODE_{proc.placement.name}_{secrets.token_hex(7)}.zip"
            zip_path = stage / zip_name
            with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
                zf.write(json_path, arcname=json_path.name)
                for child in sorted(sub_dir.iterdir()):
                    zf.write(child, arcname=f"{node_id}/{child.name}")

    def _write_widget_bundle(self, widget: _Widget, stage: Path) -> None:
        node_id = widget.placement.node_id
        metadata = {
            "node_id": node_id,
            "name": widget.placement.name,
            "node_type": "Input",
            "description": widget.placement.help_value or "",
            "category": widget.placement.category,
            "domain": "private",
            "author": None,
            "node_value": None,
            "directives": "None",
            "is_mpi": 0,
            "processing_type": "",
            "custom_value": 0,
            "file_tracking": 0,
            "limit": "",
            "files_info": [],
            "inputs": [],
            "outputs": [
                {
                    "node_output_id": widget.output_id,
                    "node_id": node_id,
                    "name": widget.output_name,
                    "type": widget.output_type,
                    "tags": "",
                    "new_id": widget.output_id,
                }
            ],
            "params": [],
            "version": self.node_version,
            "host": self.host,
        }
        with tempfile.TemporaryDirectory(dir=stage) as tmp:
            tmp_path = Path(tmp)
            json_path = tmp_path / f"{widget.placement.name}.json"
            json_path.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
            zip_name = f"NODE_{widget.placement.name}_{secrets.token_hex(7)}.zip"
            with zipfile.ZipFile(stage / zip_name, "w", zipfile.ZIP_DEFLATED) as zf:
                zf.write(json_path, arcname=json_path.name)


# ---------------------------------------------------------------------------
# CLI: list available recipes
# ---------------------------------------------------------------------------

def _list_recipes() -> list[Path]:
    return sorted(Path(__file__).resolve().parents[1].joinpath("workflows").glob("*.py"))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Build a workflow.scripps.edu zip from a recipe.",
        epilog=(
            "Each recipe under workflows/ is a small Python module that builds "
            "a Workflow object and calls .export(...). Run the recipe directly:"
            "\n\n    python workflows/<name>.py [--out dist/workflows]"
        ),
    )
    parser.add_argument(
        "--list-recipes", action="store_true",
        help="List available recipe files under workflows/.",
    )
    args = parser.parse_args(argv)

    if args.list_recipes:
        for r in _list_recipes():
            print(r.relative_to(Path(__file__).resolve().parents[1]))
        return 0

    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
