"""Shell-wrapper / environment-guard helpers.

Rationale: the workflow engine launches each node from an inherited shell
environment that may have ``PYTHONPATH``, ``PYTHONHOME``, ``PYTHONSTARTUP``,
or a stale user site-packages dir set. Without scrubbing them, the node's
Python may import packages from the wrong env (the "Franken-Python"
problem).

Existing per-node ``script.sh`` wrappers do this scrubbing inline, but the
implementation drifted: the original 7582 versions exported
``PYTHONNOUSERSITE=1`` and used ``python -I`` (full isolation), while the
newer ones (prism_pruner, orca_freq_array, thermo_aggregator) regressed to
``unset PYTHONNOUSERSITE`` and ``python -E`` (less strict).

This module owns the canonical wrapper template so every node ships with
the strict env guard and the wrapper is no longer per-node copy-paste.
"""

from __future__ import annotations

import shlex
from pathlib import Path

# The strict guard set, matching the 7582 xtb wrapper. Restored here as the
# canonical version.
_GUARD_TEMPLATE = """\
#!/bin/bash
# AUTO-GENERATED by scripps_workflow; do not edit by hand.
# Re-run `wf-import-gui` (or the wrapper-regenerator) to refresh.
set -euo pipefail

# Default to the group env Python; override with ENV_PY when needed
# (e.g. prism_pruner needs the workflow312 env on Python >= 3.12).
ENV_PY="${{ENV_PY:-{env_py}}}"

SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"

# Strict env guard: scrub everything that lets a stray PYTHONPATH /
# PYTHONHOME / user site-packages contaminate the run.
unset PYTHONHOME PYTHONPATH PYTHONSTARTUP
export PYTHONNOUSERSITE=1
{module_loads}
# `-I` = full isolation (implies -E, -s, ignores PYTHON* env vars and the
# user site dir). Strictest form available.
exec "$ENV_PY" -I -m {entrypoint_module}{fixed_args} "$@"
"""

# Default group env Python on Lucas's HPC. Centralized so we change it in
# one place if the group env path moves.
DEFAULT_ENV_PY: str = "/gpfs/group/shenvi/envs/workflow/bin/python"
PRISM_ENV_PY: str = "/gpfs/group/shenvi/envs/workflow312/bin/python"


def render_wrapper(
    *,
    entrypoint_module: str,
    env_py: str = DEFAULT_ENV_PY,
    module_loads: tuple[str, ...] = (),
    fixed_args: tuple[str, ...] = (),
) -> str:
    """Render a strict ``script.sh`` for an engine node.

    Args:
        entrypoint_module: Dotted module path whose ``main()`` is the node
            entrypoint, e.g. ``"scripps_workflow.nodes.xtb_calc"``. The
            wrapper invokes it via ``python -m`` so users do not need to
            duplicate ``script.py`` per node — the package owns the code.
        env_py: Path to the Python interpreter to use. Defaults to the
            shared workflow env.
        module_loads: Optional ``module load`` lines to insert before the
            python invocation (e.g. ``("orca/6.1.0", "openmpi/4.1")`` for
            ORCA nodes). The wrapper sources the system module-init script
            first so this works in non-interactive shells.
        fixed_args: Positional arguments baked into the wrapper, inserted
            *between* the entrypoint module and ``"$@"``. Each is
            shell-quoted via ``shlex.quote``. Used by tag-node wrappers
            to hardcode the KEY (e.g. ``fixed_args=("temperature_k",)``)
            so engine instances differ only in their wrapper, not their
            Python source — eliminating the per-instance ``KEY = "..."``
            edit pattern that produced the leading-space typo bug class.

    Returns:
        Shell script text (UTF-8) with a trailing newline.
    """
    if module_loads:
        # `module` is a shell function defined by `/etc/profile.d/modules.sh`.
        # Sourcing it first makes `module load X` work in non-interactive
        # SLURM shells.
        lines = [
            "",
            "# Make `module` available in non-interactive shells.",
            'if ! type module >/dev/null 2>&1; then',
            '    if [ -f /etc/profile.d/modules.sh ]; then',
            '        # shellcheck disable=SC1091',
            '        . /etc/profile.d/modules.sh',
            "    fi",
            "fi",
        ]
        for m in module_loads:
            lines.append(f"module load {m}")
        module_loads_block = "\n".join(lines) + "\n"
    else:
        module_loads_block = ""

    if fixed_args:
        # Leading space before each token so the format string concatenates
        # cleanly: ``...module<fixed_args> "$@"``.
        fixed_args_str = "".join(" " + shlex.quote(a) for a in fixed_args)
    else:
        fixed_args_str = ""

    return _GUARD_TEMPLATE.format(
        env_py=env_py,
        entrypoint_module=entrypoint_module,
        module_loads=module_loads_block,
        fixed_args=fixed_args_str,
    )


def write_wrapper(
    target: str | Path,
    *,
    entrypoint_module: str,
    env_py: str = DEFAULT_ENV_PY,
    module_loads: tuple[str, ...] = (),
    fixed_args: tuple[str, ...] = (),
) -> Path:
    """Write a wrapper script to ``target`` and ``chmod +x`` it."""
    p = Path(target)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        render_wrapper(
            entrypoint_module=entrypoint_module,
            env_py=env_py,
            module_loads=module_loads,
            fixed_args=fixed_args,
        ),
        encoding="utf-8",
    )
    p.chmod(0o755)
    return p
